config/routes.rb
Rails.application.routes.draw do
  resource :help
  resources :ads
  resource :blogs, only: [ :show ]
  namespace :blog do
    resources :articles
  end
  resources :qr_code, only: :show
  resources :podcasts
  namespace :users do
    resources :links
  end
  get "2532702", to: "embed#index", format: :js
  resource :session
  resource :registration
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
  resources :pages, path: "" do
    collection do
      get :features
      get :pricing
      get :subscriptions
      get :reviews
      get :stats
      get :new
      get :privacy
      get :dmca
      get :terms_of_service
      get :refunds
      get :mobile
    end
  end


  namespace :admins do
    resource :dashboard, only: [ :show ]
    resources :settings
    mount PgHero::Engine, at: "pghero"
  end

  resources :users, only: [] do
    namespace :users, path: "" do
      resources :searches, only: [ :show ], path: "search"
      resources :episodes do
        collection do
          post :skip_audio_file
        end
      end
      resources :notifications
      resources :subscriptions do
        collection do
          get :plans
          get :owner
          get :mastering_settings
          get :cohost_settings
        end
      end
      resources :directories
      resources :contributors
      resources :profiles do
        collection do
          get :referrals
        end
      end
      resource :dashboard, only: [ :show ]
      resource :stats, only: [ :show ] do
        collection do
          get :downloads
          get :locations
          get :achievements
          get :technologies
        end
      end
    end
  end
end

app/models/concerns/users/avatarable.rb
module Users::Avatarable
  extend ActiveSupport::Concern

  included do
    has_one_attached :avatar
  end

  class_methods do
    def from_avatar_token(sid)
      find_signed!(sid, purpose: :avatar)
    end
  end

  def avatar_token
    signed_id(purpose: :avatar)
  end
end

app/models/concerns/users/ransackable_attributes.rb
module RansackableAttributes
  extend ActiveSupport::Concern
  included do
    class_attribute :whitelisted_ransackable_associations
    class_attribute :whitelisted_ransackable_attributes
    class_attribute :whitelisted_ransackable_scopes

    class_attribute :default_ransackable_attributes
    self.default_ransackable_attributes = %w[id name updated_at created_at]

    def self.ransackable_associations(*_args)
      whitelisted_ransackable_associations || []
    end

    def self.ransackable_attributes(*_args)
      default_ransackable_attributes | (whitelisted_ransackable_attributes || [])
    end

    def self.ransackable_scopes(*_args)
      whitelisted_ransackable_scopes || []
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Users::Avatarable, Users::RansackableAttributes
  rolify strict: true
  has_secure_password

  has_one :setting, class_name: "Users::Setting", dependent: :delete
  has_one :notification_setting, class_name: "Users::NotificationSetting", dependent: :delete

  has_many :sessions, dependent: :destroy
  has_many :impersonator_support_sessions, class_name: "ImpersonationSession", foreign_key: :impersonator_id, dependent: :destroy
  has_many :impersonated_support_sessions, class_name: "ImpersonationSession", foreign_key: :impersonated_id, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :podcasts, dependent: :destroy
  has_many :badge_achievements, dependent: :delete_all
  has_many :badge_achievements_rewarded, class_name: "BadgeAchievement", foreign_key: :rewarder_id, inverse_of: :rewarder, dependent: :nullify
  has_many :badges, through: :badge_achievements
  has_many :ahoy_events, class_name: "Ahoy::Event", dependent: :delete_all
  has_many :ahoy_visits, class_name: "Ahoy::Visit", dependent: :delete_all
  has_many :searches, dependent: :delete_all
  has_many :downloads

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, uniqueness: true
  before_validation :set_username
  before_create :create_users_settings

  def set_username
    self.username = username&.downcase.presence || generate_username
  end

  def create_users_settings
    self.setting = Users::Setting.create
  end

  def generate_username
    self.username = loop do
      username = SecureRandom.hex(64)
      break username unless self.class.exists?(username: username)
    end
  end

  def request_impersonation_for(user_id)
    impersonated = User.find(user_id)
    impersonator_support_sessions.create!(impersonated: impersonated)
  end

  def initials
    if first_name.present? && last_name.present?
      "#{first_name.first}#{last_name.first}".upcase
    else
      initial
    end
  end

  def twitter_url
    "https://twitter.com/#{twitter_username}" if twitter_username.present?
  end

  def github_url
    "https://github.com/#{github_username}" if github_username.present?
  end


  def purge_later
    Users::PurgeJob.perform_later(self.id)
  end
end

app/models/user/avatarable.rb
module User::Avatarable
  extend ActiveSupport::Concern

  included do
    has_one_attached :avatar
  end

  class_methods do
    def from_avatar_token(sid)
      find_signed!(sid, purpose: :avatar)
    end
  end

  def avatar_token
    signed_id(purpose: :avatar)
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
    "users_"
  end
end

app/models/users/notification_setting.rb
# RailsSettings Model
class Users::NotificationSetting < RailsSettings::Base
  self.table_name = :users_notification_settings
  cache_prefix { "v1" }

  belongs_to :user

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
  #
  field :email_newsletter, type: :boolean, default: false
end

app/models/users/website.rb
module Users::Website
  def self.table_name_prefix
    "users_website_"
  end
end

app/controllers/users/contributors_controller.rb
class Users::ContributorsController < ApplicationController
  before_action :set_contributor, only: %i[ show edit update destroy ]

  # GET /users/contributors or /users/contributors.json
  def index
    @contributors = Contributor.all
  end

  # GET /users/contributors/1 or /users/contributors/1.json
  def show
  end

  # GET /users/contributors/new
  def new
    @contributor = Contributor.new
  end

  # GET /users/contributors/1/edit
  def edit
  end

  # POST /users/contributors or /users/contributors.json
  def create
    @contributor = Contributor.new(contributor_params)

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to [ :users, @contributor ], notice: "Contributor was successfully created." }
        format.json { render :show, status: :created, location: @contributor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/contributors/1 or /users/contributors/1.json
  def update
    respond_to do |format|
      if @contributor.update(contributor_params)
        format.html { redirect_to [ :users, @contributor ], notice: "Contributor was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @contributor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/contributors/1 or /users/contributors/1.json
  def destroy
    @contributor.destroy!

    respond_to do |format|
      format.html { redirect_to users_contributors_path, notice: "Contributor was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = Contributor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contributor_params
      params.fetch(:contributor, {})
    end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < Users::ManagementController
  def show
  end
end

app/controllers/users/directories_controller.rb
class Users::DirectoriesController < Users::ManagementController
  def index
  end
end

app/controllers/users/episodes_controller.rb
class Users::EpisodesController < Users::ManagementController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /users/episodes or /users/episodes.json
  def index
    set_current_tab("episodes")
    @episodes = Episode.all
  end

  # GET /users/episodes/1 or /users/episodes/1.json
  def show
  end

  # GET /users/episodes/new
  def new
    @episode = Episode.new
  end

  # GET /users/episodes/1/edit
  def edit
  end

  # POST /users/episodes or /users/episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to [ :users, @episode ], notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def skip_audio_file
    @episode = Episode.new(user: Current.user)
    respond_to do |format|
      if @episode.save
        format.html { redirect_to edit_user_users_episode_path(id: @episode.id) }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/episodes/1 or /users/episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to [ :user, :users, @episode ], notice: "Episode was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/episodes/1 or /users/episodes/1.json
  def destroy
    @episode.destroy!

    respond_to do |format|
      format.html { redirect_to user_users_episodes_path, notice: "Episode was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.fetch(:episode, {})
    end
end

app/controllers/users/links_controller.rb
class Users::LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /users/links or /users/links.json
  def index
    @links = Link.all
  end

  # GET /users/links/1 or /users/links/1.json
  def show
  end

  # GET /users/links/new
  def new
    @link = Link.new
  end

  # GET /users/links/1/edit
  def edit
  end

  # POST /users/links or /users/links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to [ :users, @link ], notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/links/1 or /users/links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to [ :users, @link ], notice: "Link was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/links/1 or /users/links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to users_links_path, notice: "Link was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.fetch(:link, {})
    end
end

app/controllers/users/management_controller.rb
class Users::ManagementController < ApplicationController
  layout "users/application"

  def set_current_tab(current_tab = "overview")
    @tab = current_tab
  end

  def set_secondary_navigation_tab(current_tab = "overview")
    @secondary_navigation_tab = current_tab
  end

  def current_podcast
    @podcast ||= Podcast.find_by(id: params[:user_id])
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < Users::ManagementController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /users/notifications or /users/notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /users/notifications/1 or /users/notifications/1.json
  def show
  end

  # GET /users/notifications/new
  def new
    @notification = Notification.new
  end

  # GET /users/notifications/1/edit
  def edit
  end

  # POST /users/notifications or /users/notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to [ :users, @notification ], notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/notifications/1 or /users/notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to [ :users, @notification ], notice: "Notification was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/notifications/1 or /users/notifications/1.json
  def destroy
    @notification.destroy!

    respond_to do |format|
      format.html { redirect_to users_notifications_path, notice: "Notification was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.fetch(:notification, {})
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < Users::ManagementController
  def referrals
  end
end

app/controllers/users/resources_controller.rb
class Users::ResourcesController < ApplicationController
end

app/controllers/users/stats_controller.rb
class Users::StatsController < Users::ManagementController
  def show
    set_secondary_navigation_tab("overview")
    @episodes = current_podcast.episodes
  end
  def downloads
    set_secondary_navigation_tab("downloads")
  end

  def technologies
    set_secondary_navigation_tab("technologies")
  end

  def locations
    set_secondary_navigation_tab("locations")
  end

  def achievements
    set_secondary_navigation_tab("achievements")
  end
end

app/controllers/users/subscriptions_controller.rb
class Users::SubscriptionsController < Users::ManagementController
  def plans
  end

  def owner
  end

  def mastering_settings
  end

  def cohost_settings
  end
end

app/views/users/stats/achievements.html.erb
<% content_for :secondary_navigation do %>
  <div class="container mx-auto">
    <%= render "users/shared/secondary_navigation" %>
  </div>
<% end %>
<%= render "users/shared/layout" do %>
  <div class="container mx-auto">
    <div class="space-y-6 py-12">
      <div class="">
        <div class="text-4xl font-bold">Your podcast is 5 days old.</div>
        <div>Upload and publish an episode to score achievements!</div>
      </div>
      <div class="grid grid-cols-2  gap-4 ">
        <div class="flex flex-col items-center justify-center bg-gray-200 rounded-lg space-y-3 py-8">
          <div class="text-xl">Podcast Downloads</div>
          <div class="font-bold text-5xl">0</div>
          <div class="text-center">You only need 10 more downloads for your next achievement.</div>
        </div>
        <div class="flex flex-col items-center justify-center bg-gray-200 rounded-lg space-y-3 py-8">
          <div class="text-xl">Episodes Published</div>
          <div class="font-bold text-5xl">0</div>
          <div class="text-center">Publish 1 more episode to receive your next achievement.</div>
        </div>
      </div>
      <div class="divide-y">
        <div class="py-6">
          <div class="font-bold text-3xl">Podcast Downloads</div>
          <div>0 achievements earned</div>
          <div>10</div>
        </div>
        <div class="py-6">
          <div class="font-bold text-3xl">Episodes Published</div>
          <div>0 achievements earned</div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/stats/downloads.html.erb
<% content_for :secondary_navigation do %>
  <div class="container mx-auto">
    <%= render "users/shared/secondary_navigation" %>
  </div>
<% end %>
<%= render "users/shared/layout" do %>
  <div class="container mx-auto">
    <div class="space-y-6 py-12">
      <div>
        0 downloads in the last 30 days.
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 bg-amber-500 rounded-lg p-8">
        <div>
          <div class="font-bold uppercase">The Podcast Predictor</div>
          <div>We forecast your next episode will receive</div>
          <div class="text-5xl font-bold">0 Downloads</div>
          <div><span class="font-bold">The Podcast Predictor</span> displays how many unique downloads we expect your next episode to have within its first 90 days of life. Learn more about predictions.</div>
        </div>
        <div class="grid items-center justify-center grid-cols-3 gap-0">
          <div>
            <div>Last 7 Days</div>
            <div>0</div>
          </div>
          <div>
            <div>Last 30 Days</div>
            <div>0</div>
          </div>
          <div>
            <div>Last 90 Days</div>
            <div>0</div>
          </div>
          <div class="col-span-3">
            <div>All Time Total Downloads</div>
            <div>0</div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/stats/show.html.erb
<% content_for :secondary_navigation do %>
  <div class="container mx-auto">
    <%= render "users/shared/secondary_navigation" %>
  </div>
<% end %>
<%= render "users/shared/layout" do %>
  <div class="container mx-auto">
    <div class="space-y-6 py-12">
      <div class="text-3xl">
        <span class="font-bold">0 downloads</span> in the <span class="font-bold">last 30 days</span>.
      </div>
      <nav>
        <ul class="flex flex-row items-center justify-center gap-4">
          <li><%= link_to "Last 7 days", user_users_stats_path(days:1), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "Last 30 days", user_users_stats_path(days:5), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "Last 90 days", user_users_stats_path(days:10), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "All time", user_users_stats_path(days: "all"), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
        </ul>
      </nav>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <div class="flex flex-row items-center gap-1 py-2">
            <div class="text-3xl font-bold">Top Episodes</div>
            <div class="text-neutral-500">(All Time)</div>
          </div>
          <div class="divide-y">
            <div class="flex flex-row items-center justify-between gap-2 py-2">
              <div>Untitled Episode</div>
              <div class="font-bold">0</div>
            </div>
            <div class="flex flex-row items-center justify-between gap-2 py-2">
              <div >Untitled Episode</div>
              <div>0</div>
            </div>
            <div class="underline flex flex-row items-center justify-between gap-2 py-2">See all episodes</div>
          </div>
        </div>
        <div>
          <div class="flex flex-row items-center gap-1 py-2">
            <div class="text-3xl font-bold">Top Apps</div>
            <div class="text-neutral-500">(Last 5 Episodes)</div>
          </div>
          <div class="divide-y">
            <div class="flex flex-row items-center justify-between gap-2 py-2">
              <div>No Apps Available</div>
            </div>
          </div>
        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 bg-yellow-500 rounded-lg p-8">
        <div>
          <div class="font-bold uppercase">The Podcast Predictor</div>
          <div>We forecast your next episode will receive</div>
          <div class="text-5xl font-bold">0 Downloads</div>
          <div><span class="font-bold">The Podcast Predictor</span> displays how many unique downloads we expect your next episode to have within its first 90 days of life. Learn more about predictions.</div>
        </div>
        <div class="grid items-center justify-center grid-cols-3 gap-0">
          <div>
            <div>Last 7 Days</div>
            <div>0</div>
          </div>
          <div>
            <div>Last 30 Days</div>
            <div>0</div>
          </div>
          <div>
            <div>Last 90 Days</div>
            <div>0</div>
          </div>
          <div class="col-span-3">
            <div>All Time Total Downloads</div>
            <div>0</div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/stats/technologies.html.erb
<% content_for :secondary_navigation do %>
  <div class="container mx-auto">
    <%= render "users/shared/secondary_navigation" %>
  </div>
<% end %>
<%= render "users/shared/layout" do %>
  <div class="container mx-auto">
    <div class="space-y-6 py-12">
      <nav>
        <ul class="flex flex-row items-center justify-center gap-4">
          <li><%= link_to "Last Episode", technologies_user_users_stats_path(count:1), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "Last 5 Episodes", technologies_user_users_stats_path(count:5), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "Last 10 Episodes", technologies_user_users_stats_path(count:10), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
          <li><%= link_to "All Episodes", technologies_user_users_stats_path(count: "all"), class: "rounded-full bg-black text-white text-xs font-bold uppercase px-2 py-2" %></li>
        </ul>
      </nav>
      <div class="grid grid-cols-3 gap-4">
        <div>
          <div class="text-3xl font-bold">Top App</div>
          <div>
            <div>No Apps Available</div>
          </div>
        </div>
        <div>
          <div class="text-3xl font-bold">Top Device</div>
          <div>
            <div>No Devices Available</div>
          </div>
        </div>
        <div>
          <div class="text-3xl font-bold">Top Category</div>
          <div>
            <div>No Types Available</div>
          </div>
        </div>
      </div>
      <div>
        <div class="text-3xl font-bold">Apps</div>
        <div>No Apps Available</div>
      </div>
    </div>
  </div>
<% end %>