config/routes.rb
Rails.application.routes.draw do
  resource :help
  resources :ads
  resource :blogs, only: [ :show ]
  namespace :blog do
    resources :articles
  end
  resources :qr_code, only: :show
  resources :podcasts
  namespace :users do
    resources :links
  end
  get "2532702", to: "embed#index", format: :js
  resource :session
  resource :registration
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
  resources :pages, path: "" do
    collection do
      get :features
      get :pricing
      get :subscriptions
      get :reviews
      get :stats
      get :new
      get :privacy
      get :dmca
      get :terms_of_service
      get :refunds
      get :mobile
    end
  end


  namespace :admins do
    resource :dashboard, only: [ :show ]
    resources :settings
    mount PgHero::Engine, at: "pghero"
  end

  resources :users, only: [] do
    namespace :users, path: "" do
      resources :searches, only: [ :show ], path: "search"
      resources :episodes do
        collection do
          post :skip_audio_file
        end
      end
      resources :notifications
      resources :subscriptions do
        collection do
          get :plans
          get :owner
          get :mastering_settings
          get :cohost_settings
        end
      end
      resources :directories
      resources :contributors
      resources :profiles do
        collection do
          get :referrals
        end
      end
      resource :dashboard, only: [ :show ]
      resource :stats, only: [ :show ] do
        collection do
          get :downloads
          get :locations
          get :achievements
          get :technologies
        end
      end
    end
  end
end

app/models/concerns/users/avatarable.rb
module Users::Avatarable
  extend ActiveSupport::Concern

  included do
    has_one_attached :avatar
  end

  class_methods do
    def from_avatar_token(sid)
      find_signed!(sid, purpose: :avatar)
    end
  end

  def avatar_token
    signed_id(purpose: :avatar)
  end
end

app/models/concerns/users/ransackable_attributes.rb
module RansackableAttributes
  extend ActiveSupport::Concern
  included do
    class_attribute :whitelisted_ransackable_associations
    class_attribute :whitelisted_ransackable_attributes
    class_attribute :whitelisted_ransackable_scopes

    class_attribute :default_ransackable_attributes
    self.default_ransackable_attributes = %w[id name updated_at created_at]

    def self.ransackable_associations(*_args)
      whitelisted_ransackable_associations || []
    end

    def self.ransackable_attributes(*_args)
      default_ransackable_attributes | (whitelisted_ransackable_attributes || [])
    end

    def self.ransackable_scopes(*_args)
      whitelisted_ransackable_scopes || []
    end
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  # has_rich_text :description

  belongs_to :podcast
  has_many :downloads
  has_many :notifications, as: :notifiable
  has_many :recommendations, as: :recommendable

  delegate :user, to: :podcast
  alias_method :author, :user

  validates :title, :episode_number, :season_number, presence: true
  validates :episode_number, uniqueness: { scope: [ :podcast_id, :season_number ] }
end

app/models/user.rb
class User < ApplicationRecord
  include Users::Avatarable, Users::RansackableAttributes
  rolify strict: true
  has_secure_password

  has_one :setting, class_name: "Users::Setting", dependent: :delete
  has_one :notification_setting, class_name: "Users::NotificationSetting", dependent: :delete

  has_many :sessions, dependent: :destroy
  has_many :impersonator_support_sessions, class_name: "ImpersonationSession", foreign_key: :impersonator_id, dependent: :destroy
  has_many :impersonated_support_sessions, class_name: "ImpersonationSession", foreign_key: :impersonated_id, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :podcasts, dependent: :destroy
  has_many :badge_achievements, dependent: :delete_all
  has_many :badge_achievements_rewarded, class_name: "BadgeAchievement", foreign_key: :rewarder_id, inverse_of: :rewarder, dependent: :nullify
  has_many :badges, through: :badge_achievements
  has_many :ahoy_events, class_name: "Ahoy::Event", dependent: :delete_all
  has_many :ahoy_visits, class_name: "Ahoy::Visit", dependent: :delete_all
  has_many :searches, dependent: :delete_all
  has_many :downloads

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, uniqueness: true
  before_validation :set_username
  before_create :create_users_settings

  def set_username
    self.username = username&.downcase.presence || generate_username
  end

  def create_users_settings
    self.setting = Users::Setting.create
  end

  def generate_username
    self.username = loop do
      username = SecureRandom.hex(64)
      break username unless self.class.exists?(username: username)
    end
  end

  def request_impersonation_for(user_id)
    impersonated = User.find(user_id)
    impersonator_support_sessions.create!(impersonated: impersonated)
  end

  def initials
    if first_name.present? && last_name.present?
      "#{first_name.first}#{last_name.first}".upcase
    else
      initial
    end
  end

  def twitter_url
    "https://twitter.com/#{twitter_username}" if twitter_username.present?
  end

  def github_url
    "https://github.com/#{github_username}" if github_username.present?
  end


  def purge_later
    Users::PurgeJob.perform_later(self.id)
  end
end

app/models/user/avatarable.rb
module User::Avatarable
  extend ActiveSupport::Concern

  included do
    has_one_attached :avatar
  end

  class_methods do
    def from_avatar_token(sid)
      find_signed!(sid, purpose: :avatar)
    end
  end

  def avatar_token
    signed_id(purpose: :avatar)
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
    "users_"
  end
end

app/models/users/notification_setting.rb
# RailsSettings Model
class Users::NotificationSetting < RailsSettings::Base
  self.table_name = :users_notification_settings
  cache_prefix { "v1" }

  belongs_to :user

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
  #
  field :email_newsletter, type: :boolean, default: false
end

app/models/users/website.rb
module Users::Website
  def self.table_name_prefix
    "users_website_"
  end
end

app/controllers/users/contributors_controller.rb
class Users::ContributorsController < ApplicationController
  before_action :set_contributor, only: %i[ show edit update destroy ]

  # GET /users/contributors or /users/contributors.json
  def index
    @contributors = Contributor.all
  end

  # GET /users/contributors/1 or /users/contributors/1.json
  def show
  end

  # GET /users/contributors/new
  def new
    @contributor = Contributor.new
  end

  # GET /users/contributors/1/edit
  def edit
  end

  # POST /users/contributors or /users/contributors.json
  def create
    @contributor = Contributor.new(contributor_params)

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to [ :users, @contributor ], notice: "Contributor was successfully created." }
        format.json { render :show, status: :created, location: @contributor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/contributors/1 or /users/contributors/1.json
  def update
    respond_to do |format|
      if @contributor.update(contributor_params)
        format.html { redirect_to [ :users, @contributor ], notice: "Contributor was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @contributor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/contributors/1 or /users/contributors/1.json
  def destroy
    @contributor.destroy!

    respond_to do |format|
      format.html { redirect_to users_contributors_path, notice: "Contributor was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = Contributor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contributor_params
      params.fetch(:contributor, {})
    end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < Users::ManagementController
  def show
  end
end

app/controllers/users/directories_controller.rb
class Users::DirectoriesController < Users::ManagementController
  def index
  end
end

app/controllers/users/episodes_controller.rb
class Users::EpisodesController < Users::ManagementController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /users/episodes or /users/episodes.json
  def index
    set_current_tab("episodes")
    @episodes = Episode.all
  end

  # GET /users/episodes/1 or /users/episodes/1.json
  def show
  end

  # GET /users/episodes/new
  def new
    @episode = Episode.new
  end

  # GET /users/episodes/1/edit
  def edit
  end

  # POST /users/episodes or /users/episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to [ :users, @episode ], notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def skip_audio_file
    @episode = Episode.new(user: Current.user)
    respond_to do |format|
      if @episode.save
        format.html { redirect_to edit_user_users_episode_path(id: @episode.id) }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/episodes/1 or /users/episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to [ :user, :users, @episode ], notice: "Episode was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/episodes/1 or /users/episodes/1.json
  def destroy
    @episode.destroy!

    respond_to do |format|
      format.html { redirect_to user_users_episodes_path, notice: "Episode was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.fetch(:episode, {})
    end
end

app/controllers/users/links_controller.rb
class Users::LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /users/links or /users/links.json
  def index
    @links = Link.all
  end

  # GET /users/links/1 or /users/links/1.json
  def show
  end

  # GET /users/links/new
  def new
    @link = Link.new
  end

  # GET /users/links/1/edit
  def edit
  end

  # POST /users/links or /users/links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to [ :users, @link ], notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/links/1 or /users/links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to [ :users, @link ], notice: "Link was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/links/1 or /users/links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to users_links_path, notice: "Link was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.fetch(:link, {})
    end
end

app/controllers/users/management_controller.rb
class Users::ManagementController < ApplicationController
  layout "users/application"

  def set_current_tab(current_tab = "overview")
    @tab = current_tab
  end

  def set_secondary_navigation_tab(current_tab = "overview")
    @secondary_navigation_tab = current_tab
  end

  def current_podcast
    @podcast ||= Podcast.find_by(id: params[:user_id])
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < Users::ManagementController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /users/notifications or /users/notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /users/notifications/1 or /users/notifications/1.json
  def show
  end

  # GET /users/notifications/new
  def new
    @notification = Notification.new
  end

  # GET /users/notifications/1/edit
  def edit
  end

  # POST /users/notifications or /users/notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to [ :users, @notification ], notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/notifications/1 or /users/notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to [ :users, @notification ], notice: "Notification was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/notifications/1 or /users/notifications/1.json
  def destroy
    @notification.destroy!

    respond_to do |format|
      format.html { redirect_to users_notifications_path, notice: "Notification was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.fetch(:notification, {})
    end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < Users::ManagementController
  def referrals
  end
end

app/controllers/users/resources_controller.rb
class Users::ResourcesController < ApplicationController
end

app/controllers/users/stats_controller.rb
class Users::StatsController < Users::ManagementController
  def show
    set_secondary_navigation_tab("overview")
    @episodes = current_podcast.episodes
  end
  def downloads
    set_secondary_navigation_tab("downloads")
  end

  def technologies
    set_secondary_navigation_tab("technologies")
  end

  def locations
    set_secondary_navigation_tab("locations")
  end

  def achievements
    set_secondary_navigation_tab("achievements")
  end
end

app/views/users/episodes/_episode.html.erb
<div id="<%= dom_id episode %>" class="w-full sm:w-auto my-5 space-y-5">
</div>

app/views/users/episodes/_form.html.erb
<%= form_with(model: [:user, :users, episode], class: "contents") do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>
      <ul class="list-disc ml-6">
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid grid-cols-12 gap-12">
    <div class="col-span-8">
      <div class="bg-gray-100 rounded-lg p-16 py-32  ">
        <div class="text-4xl font-bold text-center">Drags audio file here or choose a file</div>
      </div>
      <div class="text-center">Upload an audio file or <%= button_to "delete this episode", user_users_episode_path(id: episode.id), method: :delete, data: { turbo_method: :delete }, class: "underline" %>.</div>
      <div class="flex flex-col gap-1">
        <%= form.label :title, class: "font-bold" %>
        <%= form.text_field :title, class: "outline rounded p-2" %>
      </div>
      <div class="flex flex-col gap-1">
        <%= form.label :description, class: "font-bold" %>
        <%= form.rich_textarea :description, class: "outline rounded p-2" %>
      </div>
      <div class="flex flex-col gap-1">
        <%= form.label :explicit_content,"Explicit Content", class: "font-bold" %>
        <div class="flex flex-row items-center gap-1">
          <%= form.checkbox "Explicit Content", class: "font-bold" %>
          <div>This episode contains explicit material.</div>
        </div>
      </div>
    </div>
    <div class="col-span-4">
      <div>Episodes can not be published until an audio file has been uploaded.</div>
      <div class="flex flex-col gap-4 rounded-lg overflow-clip bg-gray-100">
        <div class="bg-black text-white p-2">When do you want to publish?</div>
        <div class="py-4">
          <div class="leading-4 px-3 py-2">
            <div class="font-bold">Leave Unpublished</div>
            <div class="text-sm text-neutral-500">Manually publish when you're ready.</div>
          </div>
          <div class="leading-4 px-3 py-2">
            <div class="font-bold">Publish Immediately</div>
            <div class="text-sm text-neutral-500">Goes live after processing is complete.</div>
          </div>
          <div class="leading-4 px-3 py-2">
            <div class="font-bold">Schedule for Future</div>
            <div class="text-sm text-neutral-500">Pick a date and time for release.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/episodes/_secondary_navigation.html.erb
<nav class="flex flex-row items-center gap-2">
  <ul class="flex flex-row items-center gap-6 border-b w-full p-2">
    <li><%= link_to "All Episodes", user_users_episodes_path, class: "py-2 #{@secondary_navigation_tab == 'overview' ? 'border-b-2 border-black' : ''}" %></li>
    <li>
      <div><%= link_to "Dynamic Content", downloads_user_users_stats_path, class: "py-2 #{@secondary_navigation_tab == 'downloads' ? 'border-b-2 border-black' : ''}" %></div>
    </li>
    <li>
      <div><%= link_to "Fan Mail", technologies_user_users_stats_path, class: "py-2 #{@secondary_navigation_tab == 'technologies' ? 'border-b-2 border-black' : ''}" %></div>
    </li>
    <li>
      <div><%= link_to "Magic Mastering", locations_user_users_stats_path, class: "py-2 #{@secondary_navigation_tab == 'locations' ? 'border-b-2 border-black' : ''}" %></div>
    </li>
    <li>
      <div><%= link_to "Cohost AI", achievements_user_users_stats_path, class: "py-2 #{@secondary_navigation_tab == 'achievements' ? 'border-b-2 border-black' : ''}" %></div>
    </li>
  </ul>
</nav>

app/views/users/episodes/_table_tr.html.erb
<tr>
    <td>Date</td>
    <td>
        <div>Name</div>
        <div>Since you are on a free account, this episode will be deleted in <span>90</span> days. <span>Upgrade to save</span></div>
    </td>
</tr>

app/views/users/episodes/edit.html.erb
<% content_for :title, "Editing episode" %>
<div class="container mx-auto">
  <div>
    <h1 class="font-bold text-4xl">Editing episode</h1>
    <%= render "form", episode: @episode %>
    <%= link_to "Show this episode", [:user, :users, @episode], class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "Back to episodes", user_users_episodes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  </div>
</div>

app/views/users/episodes/index.html.erb
<% content_for :secondary_navigation do %>
  <div class="container mx-auto">
    <%= render "secondary_navigation" %>
  </div>
<% end %>
<% content_for :title, "Episodes" %>
<div class="container mx-auto">
  <div class="space-y-6 py-12">
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">All Episodes</h1>
      <%= link_to "Upload a New Episode", new_user_users_episode_path, class: "rounded-md px-3 py-2 bg-black  text-white block font-medium" %>
    </div>
    <div id="episodes" class="min-w-full divide-y divide-gray-200 space-y-5">
      <div>
        <div class="hidden md:flex gap-8 justify-between items-center py-6 px-0  pb-3 text-2xs text-gray uppercase border-b ">
          <div class="w-full grid grid-cols-12 items-center">
            <div class="md:col-span-8 flex flex-col md:flex-row md:gap-4">
              <div class="basis-28">Date</div>
              <div class="">Episode</div>
            </div>
            <div class="md:col-start-9 md:col-span-2 col-start-1 col-end-1 text-center">Duration</div>
            <div class="md:col-start-11 md:col-span-2 col-start-1 col-end-1 text-center">Downloads</div>
          </div>
          <div class="basis-[65px] grow-0 shrink-0"></div>
        </div>
        <% if @episodes.any? %>
          <% @episodes.each do |episode| %>
            <article id="episode_17771625" aria-label="Untitled Episode" class=" episode episode--not_live flex gap-8 justify-between items-center py-4 md:group-[.current-episodes]:py-8 md:py-6 px-5 md:group-[.current-episodes]:px-8 md:px-0 relative">
              <div class="w-full grid md:grid-cols-12 grid-cols-1 items-center">
                <div class="md:col-span-8 flex flex-col md:flex-row md:items-center md:gap-6">
                  <div class="hidden w-16 md:group-[.episode-history]:hidden md:block">
                    <div class="episode__date w-16 flex flex-col text-center bg-gray-100 rounded-md group-[.cohost-processing]:!border-purple">
                      <div class="month py-0.5 text-[10px] text-white font-light bg-green-600 rounded-t-[5px] tracking-wider uppercase group-[.cohost-processing]:!bg-purple-600">Sep</div>
                      <div class="day pt-3 pb-2 text-[32px] font-light leading-6 group-[.cohost-processing]:text-purple"> 2</div>
                      <div class="day_of_week pb-1 text-[8px] text-gray tracking-wide uppercase ">Tuesday</div>
                    </div>
                  </div>
                  <div class="md:group-[.episode-history]:flex items-center">
                    <div class="flex items-center">
                      <div class="hidden native:flex gap-1 text-xs font-bold">
                      </div>
                      <div class="md:group-[.current-episodes]:hidden native:hidden past-episodes-date pr-2 md:text-base text-xs text-gray md:font-normal font-medium">
                        <div class="md:w-28">
                          Sep  2, 2025
                        </div>
                      </div>
                      <div class="md:group-[.episode-history]:hidden native:hidden episode__status--not_live md:pl-0 text-xs font-medium uppercase">
                        <span class="pr-2">Not Live</span>
                      </div>
                      <div class="hidden grow md:group-[.episode-history]:block relative  status-dot md:w-2 md:h-2 rounded-full px-1" aria-role="status">
                        <span class="sr-only">Episode is not_live</span>
                      </div>
                      <div class="md:group-[.episode-history]:hidden flex w-auto gap-1 items-center">
                      </div>
                    </div>
                    <div class="md:group-[.episode-history]:ml-1">
                      <div class="group-[.episode-history]:flex flex-col md:flex-row items-start md:gap-2">
                        <div class="flex flex-wrap items-center leading-tight">
                          Waiting for audio file...
                          <%= link_to "Untitled Episode",  edit_user_users_episode_path(id: episode.id), title: "Untitled Episode", class: "text-green-800 md:font-normal font-bold" %>
                          <%= link_to "Untitled Episode",  edit_user_users_episode_path(id: episode.id), title: "Untitled Episode", class: "absolute inset-0", tabindex: "-1", "aria-label": "Untitled Episode" %>
                        </div>
                      </div>
                      <div class="free_account_notice text-xs text-gray relative z-10">
                        Since you are on a free account, this episode will be deleted in <strong class="text-red">90 days</strong>.
                        <a class="link-dark-green native:hidden" href="https://www.buzzsprout.com/admin/2532702/subscription/plans">Upgrade to save</a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="hidden native:flex items-center gap-1 native:pt-1 text-xs text-gray font-medium">
                  <div class="status-dot md:hidden px-1 w-2 h-2 rounded-full" aria-role="status">
                    <span class="sr-only">Episode is not_live</span>
                  </div>
                  <div>
                    Sep  2, 2025
                  </div>
                </div>
              </div>
              <div class="grow-0 shrink-0 md:basis-[65px]">
                <div class="hidden md:group-[.episode-history]:grid grid-cols-2 grid-auto-rows gap-1 justify-center items-center">
                </div>
                <img src="/images/artworks_cover.jpg" class="w-[50px] h-[50px] rounded md:group-[.episode-history]:hidden hidden md:block" loading="lazy">
              </div>
            </article>
          <% end %>
        <% else %>
          <div class="text-center my-10">
            <div colspan="4" >No episodes found.</div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/episodes/new.html.erb
<% content_for :title, "New episode" %>
<div class="container mx-auto">
  <div class="bg-neutral-200 rounded-lg p-16 py-32 flex flex-col items-center justify-center">
    <div class="text-4xl font-bold text-center">Drags audio file here or choose a file</div>
      <%= button_to "Skip and upload later", skip_audio_file_user_users_episodes_path, method: :post, data: { turbo_method: :post }, class: "text-neutral-500 text-sm text-center" %>
  </div>
</div>

app/views/users/episodes/show.html.erb
<% content_for :title, "Showing episode" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing episode</h1>

  <%= render @episode %>

  <%= link_to "Edit this episode", edit_users_episode_path(@episode), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to episodes", users_episodes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this episode", [:users, @episode], method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>